### ISSUE TITLE
python3 grid2d problem

### ISSUE THREAD

**Issue by andrewgait** [INCF/csa#15]
Hello, the grid2d function (and perhaps other gridding functions too, I haven't checked them) are broken in python3 due to integer divides being different than in python2.  To fix the grid2d function, lines 28-29 of geometry.py need to be changed to:

`g = lambda i: \`
`        (x0 + xScale * (i % width), y0 + yScale * (i // width))`

and then everything seems to work correctly.

**Comment by mdjurfeldt** [comment]
Fixed in commit 29cf653.

Thank you!
