### ISSUE TITLE
/usr/bin/ld: cannot find -lpyneurosim

### ISSUE THREAD

**Issue by jianyongpi** [INCF/csa#21]
sudo ./configure --with-libneurosim=/usr/local

sudo make
the result is :
/usr/bin/ld: cannot find -lpyneurosim

**Comment by jianyongpi** [comment]
I configure libneurosim --with-python=3
I think CSA should support python3,but the lpyneurosim belong to python2, how can I configure CSA support python3?

**Comment by mdjurfeldt** [comment]
You should now (git master + version 0.1.10) be able to do:

./configure --with-python=python3

Closing
