### ISSUE TITLE
new version on pypi.org

### ISSUE THREAD

**Issue by bjuergens** [INCF/csa#22]
Will there be a new version on pypi?

I myself need #19 to be on pypi, but more changes were accumulated since the last release in 2018, which should also be on pypi, I think: #10 #18 #15

**Comment by poupa29** [comment]
Dear PyNN developers, Dear @mdjurfeldt ,

Our PyNN installation in the Neurorobotics Platform is broken because of one of the issues mentioned by bjuergens above (#19). Could you tell us if a new build in pypi can be planned in the next days?

Axel von Arnim
HBP Neurorobotics Platform

**Comment by mdjurfeldt** [comment]
I will make sure that this is fixed within a couple of days.

Best regards,
Mikael

Den mån 20 jan. 2020 13:42poupa29 <notifications@github.com> skrev:

**Comment by mdjurfeldt** [comment]
Version 1.1.10 is now uploaded to pypi.

Closing ticket.
