### ISSUE TITLE
Display error while `show(full)` and `show(empty)`

### ISSUE THREAD

**Issue by yuxuan-z19** [INCF/csa#23]
Correct me if i'm wrong, but how could `show(full)` and `show(empty)` behave EXACTLY THE SAME ???

![屏幕截图 2022-11-13 210119](https://user-images.githubusercontent.com/68550432/201522905-bdff328f-2de6-4615-857f-7345b67e4b96.png)

**Comment by mdjurfeldt** [comment]
show() normalized the image giving the "background color" also to an image filled with ones.

This is fixed in commit 006a56e5 and will be part of next release.

Thank you for the bug report!
