### ISSUE TITLE
v0.1.7 on pypi.org

### ISSUE THREAD

**Issue by espenhgn** [INCF/csa#8]
Hi @mdjurfeldt 
Would you consider making a new release of csa and upload to pypi.org based on the current master?
The version on there is quite old (Dec. 2012), and a new release would simplify installation of for example LFPy using pip (where dependency_links are not automatically used). 

Should be quite easy:
```
pip install twine
cd <csa>
python setup.py sdist
twine upload dist/*
```

**Comment by mdjurfeldt** [comment]
v0.1.8 is now released. The sourcefiles (without libpycsa which establishes the connection to other simulators through libneurosim) are uploaded to pypi.
